import React, { useState, useRef } from 'react';
import * as BABYLON from '@babylonjs/core';
import useSceneStore, { Light, LightType } from '../store/sceneStore';

interface LightingPanelProps {
  className?: string;
}

const LightingPanel: React.FC<LightingPanelProps> = ({ className = '' }) => {
  const { 
    scene, 
    lights, 
    addLight, 
    removeLight, 
    updateLight, 
    selectLight, 
    selectedLightId,
    environmentIntensity,
    setEnvironmentIntensity,
    /* environmentTexture, */ // Unused but kept for reference
    setEnvironmentTexture
  } = useSceneStore();
  
  const [showAddMenu, setShowAddMenu] = useState(false);
  const [newHdrUrl, setNewHdrUrl] = useState<string>('');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Create a new light in the scene
  const handleAddLight = (type: LightType) => {
    if (!scene) return;
    
    let newLight: Light | null = null;
    let babylonLight: BABYLON.Light | null = null;

    switch (type) {
      case 'directional':
        babylonLight = new BABYLON.DirectionalLight(
          `directional-${lights.length}`,
          new BABYLON.Vector3(0, -1, 0),
          scene
        );
        newLight = {
          id: '', // Will be generated by store
          type: 'directional',
          name: `Directional ${lights.length + 1}`,
          intensity: 1.0,
          direction: { x: 0, y: -1, z: 0 },
          color: '#FFFFFF',
          babylonRef: babylonLight
        };
        break;
        
      case 'point':
        babylonLight = new BABYLON.PointLight(
          `point-${lights.length}`,
          new BABYLON.Vector3(0, 3, 0),
          scene
        );
        newLight = {
          id: '', // Will be generated by store
          type: 'point',
          name: `Point ${lights.length + 1}`,
          intensity: 1.0,
          position: { x: 0, y: 3, z: 0 },
          color: '#FFFFFF',
          range: 100,
          babylonRef: babylonLight
        };
        break;
        
      case 'spot':
        const spotDirection = new BABYLON.Vector3(0, -1, 0);
        const spotPosition = new BABYLON.Vector3(0, 5, 0);
        babylonLight = new BABYLON.SpotLight(
          `spot-${lights.length}`,
          spotPosition,
          spotDirection,
          Math.PI / 4,
          2,
          scene
        );
        newLight = {
          id: '', // Will be generated by store
          type: 'spot',
          name: `Spot ${lights.length + 1}`,
          intensity: 1.0,
          position: { x: 0, y: 5, z: 0 },
          direction: { x: 0, y: -1, z: 0 },
          color: '#FFFFFF',
          angle: Math.PI / 4,
          exponent: 2,
          range: 100,
          babylonRef: babylonLight
        };
        break;
        
      case 'hdr':
        // We'll handle HDR environment creation separately
        newLight = {
          id: '', // Will be generated by store
          type: 'hdr',
          name: `Environment ${lights.length + 1}`,
          intensity: 1.0,
          color: '#FFFFFF',
          environmentTexture: newHdrUrl || 'https://assets.babylonjs.com/environments/studio.env'
        };
        
        // Create an HDR environment if we have a scene
        if (scene && newLight.environmentTexture) {
          const hdrTexture = new BABYLON.CubeTexture(newLight.environmentTexture, scene);
          scene.environmentTexture = hdrTexture;
          scene.environmentIntensity = newLight.intensity;
        }
        break;
    }

    if (newLight) {
      addLight(newLight);
    }
    
    setShowAddMenu(false);
  };

  // Handle HDR texture file upload
  const handleHdrFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = (event) => {
        if (event.target && event.target.result) {
          const url = URL.createObjectURL(file);
          setNewHdrUrl(url);
          handleAddLight('hdr');
        }
      };
      reader.readAsDataURL(file);
    }
  };
  
  // Update a light's properties
  const handleUpdateLight = (id: string, updates: Partial<Light>) => {
    updateLight(id, updates);
  };

  // Format a Vector3 for display
  const formatVector = (vector: { x: number; y: number; z: number } | undefined) => {
    if (!vector) return 'N/A';
    return `(${vector.x.toFixed(1)}, ${vector.y.toFixed(1)}, ${vector.z.toFixed(1)})`;
  };
  
  /* 
  // These color conversion functions are kept for future use but commented out to avoid lint warnings
  
  // Convert hex color to RGB values for sliders
  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 255, g: 255, b: 255 };
  };

  // Convert RGB values to hex color
  const rgbToHex = (r: number, g: number, b: number) => {
    return "#" + ((1 << 24) + (r << 16) + (g << 8) + b).toString(16).slice(1);
  };
  */

  // Get short type label
  const getLightTypeLabel = (type: LightType) => {
    switch(type) {
      case 'directional': return 'Dir';
      case 'point': return 'Point';
      case 'spot': return 'Spot';
      case 'hdr': return 'HDR';
    }
  };

  // Render a light item in the list
  const renderLightItem = (light: Light) => {
    const isSelected = selectedLightId === light.id;
    
    return (
      <div key={light.id} className={`mb-4 p-3 rounded-md ${isSelected ? 'bg-sphaire-purple-light bg-opacity-20 border border-sphaire-purple' : 'bg-sphaire-dark-lighter'}`}>
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center">
            <div 
              className="w-4 h-4 rounded-full mr-2" 
              style={{ backgroundColor: light.color }}
            />
            <h4 className="font-medium">{light.name}</h4>
          </div>
          <div className="flex items-center">
            <span className="text-xs px-2 py-1 bg-sphaire-purple rounded-md mr-2">
              {getLightTypeLabel(light.type)}
            </span>
            <button 
              onClick={() => selectLight(isSelected ? null : light.id)}
              className="p-1 rounded-md hover:bg-sphaire-purple transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
            </button>
            <button 
              onClick={() => removeLight(light.id)}
              className="p-1 rounded-md hover:bg-red-500 hover:bg-opacity-20 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        
        {/* Basic properties for all light types */}
        <div className="grid grid-cols-2 gap-2 mb-2">
          <div className="col-span-2">
            <label className="block text-xs text-sphaire-pink-light mb-1">Name</label>
            <input
              type="text"
              className="input w-full py-1 text-sm"
              value={light.name}
              onChange={(e) => handleUpdateLight(light.id, { name: e.target.value })}
            />
          </div>
        </div>
        
        {/* Intensity slider - common to all lights */}
        <div className="mb-3">
          <div className="flex justify-between items-center mb-1">
            <label className="text-xs text-sphaire-pink-light">Intensity</label>
            <span className="text-xs">{light.intensity.toFixed(2)}</span>
          </div>
          <input
            type="range"
            className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
            min="0"
            max="2"
            step="0.01"
            value={light.intensity}
            onChange={(e) => handleUpdateLight(light.id, { intensity: parseFloat(e.target.value) })}
          />
        </div>

        {/* Color picker */}
        <div className="mb-3">
          <label className="block text-xs text-sphaire-pink-light mb-1">Color</label>
          <div className="flex items-center">
            <input
              type="color"
              className="w-8 h-8 rounded mr-2 border border-sphaire-purple cursor-pointer"
              value={light.color}
              onChange={(e) => handleUpdateLight(light.id, { color: e.target.value })}
            />
            <input
              type="text"
              className="input w-full py-1 text-sm"
              value={light.color}
              onChange={(e) => handleUpdateLight(light.id, { color: e.target.value })}
            />
          </div>
        </div>

        {/* Position for point and spot lights */}
        {(light.type === 'point' || light.type === 'spot') && light.position && (
          <div className="mb-3">
            <label className="block text-xs text-sphaire-pink-light mb-1">Position: {formatVector(light.position)}</label>
            <div className="grid grid-cols-3 gap-2">
              <div>
                <label className="text-xs">X</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-10"
                  max="10"
                  step="0.1"
                  value={light.position.x}
                  onChange={(e) => {
                    if (light.position) {
                      handleUpdateLight(light.id, { 
                        position: { 
                          x: parseFloat(e.target.value),
                          y: light.position.y, 
                          z: light.position.z 
                        } 
                      });
                    }
                  }}
                />
              </div>
              <div>
                <label className="text-xs">Y</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-10"
                  max="10"
                  step="0.1"
                  value={light.position.y}
                  onChange={(e) => {
                    if (light.position) {
                      handleUpdateLight(light.id, { 
                        position: { 
                          x: light.position.x,
                          y: parseFloat(e.target.value), 
                          z: light.position.z 
                        } 
                      });
                    }
                  }}
                />
              </div>
              <div>
                <label className="text-xs">Z</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-10"
                  max="10"
                  step="0.1"
                  value={light.position.z}
                  onChange={(e) => {
                    if (light.position) {
                      handleUpdateLight(light.id, { 
                        position: { 
                          x: light.position.x,
                          y: light.position.y, 
                          z: parseFloat(e.target.value) 
                        } 
                      });
                    }
                  }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Direction for directional and spot lights */}
        {(light.type === 'directional' || light.type === 'spot') && light.direction && (
          <div className="mb-3">
            <label className="block text-xs text-sphaire-pink-light mb-1">Direction: {formatVector(light.direction)}</label>
            <div className="grid grid-cols-3 gap-2">
              <div>
                <label className="text-xs">X</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-1"
                  max="1"
                  step="0.1"
                  value={light.direction.x}
                  onChange={(e) => {
                    if (light.direction) {
                      handleUpdateLight(light.id, { 
                        direction: { 
                          x: parseFloat(e.target.value),
                          y: light.direction.y, 
                          z: light.direction.z 
                        } 
                      });
                    }
                  }}
                />
              </div>
              <div>
                <label className="text-xs">Y</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-1"
                  max="1"
                  step="0.1"
                  value={light.direction.y}
                  onChange={(e) => {
                    if (light.direction) {
                      handleUpdateLight(light.id, { 
                        direction: { 
                          x: light.direction.x,
                          y: parseFloat(e.target.value), 
                          z: light.direction.z 
                        } 
                      });
                    }
                  }}
                />
              </div>
              <div>
                <label className="text-xs">Z</label>
                <input
                  type="range"
                  className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
                  min="-1"
                  max="1"
                  step="0.1"
                  value={light.direction.z}
                  onChange={(e) => {
                    if (light.direction) {
                      handleUpdateLight(light.id, { 
                        direction: { 
                          x: light.direction.x,
                          y: light.direction.y, 
                          z: parseFloat(e.target.value) 
                        } 
                      });
                    }
                  }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Angle for spot lights */}
        {light.type === 'spot' && light.angle !== undefined && (
          <div className="mb-3">
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs text-sphaire-pink-light">Angle</label>
              <span className="text-xs">{(light.angle * (180/Math.PI)).toFixed(0)}°</span>
            </div>
            <input
              type="range"
              className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
              min="0.1"
              max="1.5"
              step="0.01"
              value={light.angle}
              onChange={(e) => handleUpdateLight(light.id, { angle: parseFloat(e.target.value) })}
            />
          </div>
        )}

        {/* Exponent for spot lights */}
        {light.type === 'spot' && light.exponent !== undefined && (
          <div className="mb-3">
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs text-sphaire-pink-light">Exponent</label>
              <span className="text-xs">{light.exponent.toFixed(1)}</span>
            </div>
            <input
              type="range"
              className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
              min="1"
              max="10"
              step="0.1"
              value={light.exponent}
              onChange={(e) => handleUpdateLight(light.id, { exponent: parseFloat(e.target.value) })}
            />
          </div>
        )}

        {/* Range for point and spot lights */}
        {(light.type === 'point' || light.type === 'spot') && light.range !== undefined && (
          <div className="mb-3">
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs text-sphaire-pink-light">Range</label>
              <span className="text-xs">{light.range.toFixed(0)}</span>
            </div>
            <input
              type="range"
              className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
              min="1"
              max="200"
              step="1"
              value={light.range}
              onChange={(e) => handleUpdateLight(light.id, { range: parseFloat(e.target.value) })}
            />
          </div>
        )}

        {/* HDR environment texture */}
        {light.type === 'hdr' && (
          <div className="mb-3">
            <label className="block text-xs text-sphaire-pink-light mb-1">Environment Map</label>
            {light.environmentTexture && (
              <div className="bg-sphaire-dark p-2 rounded mb-2 text-xs overflow-hidden text-ellipsis">
                {light.environmentTexture.substring(0, 30)}...
              </div>
            )}
            <input
              type="text"
              placeholder="Enter HDR texture URL"
              className="input w-full py-1 text-sm mb-2"
              value={light.environmentTexture || ''}
              onChange={(e) => handleUpdateLight(light.id, { environmentTexture: e.target.value })}
            />
            <button 
              onClick={() => {
                if (scene && light.environmentTexture) {
                  const hdrTexture = new BABYLON.CubeTexture(light.environmentTexture, scene);
                  scene.environmentTexture = hdrTexture;
                }
              }}
              className="btn-primary text-sm w-full"
            >
              Apply Texture
            </button>
          </div>
        )}
      </div>
    );
  };

  return (
    <div className={`p-4 ${className}`}>
      <div className="flex justify-between items-center mb-6">
        <h3 className="text-xl font-medium text-gradient">Lighting</h3>
        <button 
          className="btn-primary text-sm flex items-center"
          onClick={() => setShowAddMenu(!showAddMenu)}
        >
          <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          Add Light
        </button>
      </div>

      {/* Add light menu */}
      {showAddMenu && (
        <div className="bg-sphaire-dark-lighter p-3 rounded-md mb-4 border border-sphaire-purple border-opacity-30">
          <h4 className="text-sm font-medium text-sphaire-pink-light mb-3">Select light type</h4>
          <div className="grid grid-cols-2 gap-2">
            <button 
              onClick={() => handleAddLight('directional')}
              className="btn-secondary text-xs py-2"
            >
              Directional
            </button>
            <button 
              onClick={() => handleAddLight('point')}
              className="btn-secondary text-xs py-2"
            >
              Point
            </button>
            <button 
              onClick={() => handleAddLight('spot')}
              className="btn-secondary text-xs py-2"
            >
              Spot
            </button>
            <button 
              onClick={() => {
                // Trigger file input for HDR environment
                if (fileInputRef.current) {
                  fileInputRef.current.click();
                } else {
                  handleAddLight('hdr');
                }
              }}
              className="btn-secondary text-xs py-2"
            >
              HDR Environment
            </button>
          </div>
          {/* Hidden file input for HDR environment */}
          <input 
            ref={fileInputRef}
            type="file" 
            accept=".hdr,.env"
            className="hidden"
            onChange={handleHdrFileUpload}
          />
          
          <div className="mt-2 text-xs text-gray-400">
            <p>You can also enter an HDR URL directly by selecting HDR Environment</p>
          </div>
        </div>
      )}

      {/* List of lights */}
      <div className="mb-4">
        {lights.length === 0 && (
          <div className="text-center py-8 text-gray-400">
            <svg className="w-12 h-12 mx-auto mb-3 text-sphaire-purple-light opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
            </svg>
            <p>No lights added yet. Click "Add Light" to create one.</p>
          </div>
        )}
        
        {lights.map(renderLightItem)}
      </div>

      {/* Scene ambient light settings */}
      {scene && (
        <div className="bg-sphaire-dark-lighter p-3 rounded-md border border-sphaire-purple border-opacity-30">
          <h4 className="text-sm font-medium text-sphaire-pink-light mb-2">Scene Lighting</h4>
          
          <div className="mb-3">
            <div className="flex justify-between items-center mb-1">
              <label className="text-xs text-sphaire-pink-light">Environment Intensity</label>
              <span className="text-xs">{environmentIntensity.toFixed(2)}</span>
            </div>
            <input
              type="range"
              className="w-full accent-sphaire-pink-light h-1 rounded appearance-none bg-sphaire-dark"
              min="0"
              max="3"
              step="0.05"
              value={environmentIntensity}
              onChange={(e) => setEnvironmentIntensity(parseFloat(e.target.value))}
            />
          </div>
          
          {/* Scene environment selection */}
          <div className="mb-2">
            <label className="block text-xs text-sphaire-pink-light mb-1">Environment Preset</label>
            <select 
              className="input w-full py-1 text-sm"
              onChange={(e) => {
                if (scene && e.target.value) {
                  const hdrTexture = new BABYLON.CubeTexture(e.target.value, scene);
                  scene.environmentTexture = hdrTexture;
                  setEnvironmentTexture(e.target.value);
                }
              }}
            >
              <option value="">-- Select Environment --</option>
              <option value="https://assets.babylonjs.com/environments/studio.env">Studio</option>
              <option value="https://assets.babylonjs.com/environments/environmentSpecular.env">Specular</option>
              <option value="https://assets.babylonjs.com/environments/parking.env">Parking</option>
            </select>
          </div>
        </div>
      )}
    </div>
  );
};

export default LightingPanel;
